In [3]:
# rename
import numpy as np
import pandas as pd
data = {
    "experience":[1,2,3,4,5,6,7,8,9,np.nan],
    "salary":[np.nan,200,300,400,np.nan,600,700,800,900,1000]
}
 
df = pd.DataFrame(data)
 
# rename
df.rename(columns={"experience":"hands_on_experience","salary":"Amount"},inplace=True)
print(df)

   hands_on_experience  Amount
0                  1.0     NaN
1                  2.0   200.0
2                  3.0   300.0
3                  4.0   400.0
4                  5.0     NaN
5                  6.0   600.0
6                  7.0   700.0
7                  8.0   800.0
8                  9.0   900.0
9                  NaN  1000.0

In [9]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [10]:
df.head()

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1

In [12]:
df.tail(2)

   Emp_ID  Name Department  Salary  Experience
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [6]:
df.describe()

           Emp_ID        Salary  Experience
count    6.000000      6.000000    6.000000
mean   103.500000  51666.666667    3.000000
std      1.870829   5316.640543    1.414214
min    101.000000  45000.000000    1.000000
25%    102.250000  48500.000000    2.250000
50%    103.500000  51000.000000    3.000000
75%    104.750000  54250.000000    3.750000
max    106.000000  60000.000000    5.000000

In [7]:
df.isnull().sum()

Emp_ID        0
Name          0
Department    0
Salary        0
Experience    0
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      6 non-null      int64
 1   Name        6 non-null      str
 2   Department  6 non-null      str
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), str(2)
memory usage: 372.0 bytes

In [13]:
df.shape

(6, 5)

In [15]:
df.rename(columns = {"Emp_ID":"Employed_ID"},inplace = True)

In [16]:
df

   Employed_ID  Name Department  Salary  Experience
0          101  Amit         IT   50000           2
1          102  Riya         HR   45000           3
2          103   Raj    Finance   60000           5
3          104  Sara         IT   55000           4
4          105  John      Sales   48000           1
5          106  Neha         HR   52000           3

In [27]:
# select cols
print(df['Employed_ID'])
 
# select col store in variable
abc = df['Employed_ID']
print(abc)

0   -299
1   -298
2   -297
3   -296
4   -295
5   -294
Name: Employed_ID, dtype: int64
0   -299
1   -298
2   -297
3   -296
4   -295
5   -294
Name: Employed_ID, dtype: int64

In [28]:
# #cols value change
# df['Employed_ID'] = [1,2,3,4,5,6]
# df['Employed_ID']

In [29]:
df['Employed_ID'] = df['Employed_ID']-100

In [30]:
df['Employed_ID']

0   -399
1   -398
2   -397
3   -396
4   -395
5   -394
Name: Employed_ID, dtype: int64

In [31]:
#add new columns
df['Amount'] = df['Salary']
df

   Employed_ID  Name Department  Salary  Experience  Amount
0         -399  Amit         IT   50000           2   50000
1         -398  Riya         HR   45000           3   45000
2         -397   Raj    Finance   60000           5   60000
3         -396  Sara         IT   55000           4   55000
4         -395  John      Sales   48000           1   48000
5         -394  Neha         HR   52000           3   52000

In [ ]:
# add new columns manually
df['increment'] = [10,20,30,40,50,60]
df

TypeError: 'DataFrame' object is not callable

In [38]:
#drop cols
df.drop("Employed_ID",axis = 1,inplace=True)
df

   Name Department  Salary  Experience  Amount  increment
0  Amit         IT   50000           2   50000         10
1  Riya         HR   45000           3   45000         20
2   Raj    Finance   60000           5   60000         30
3  Sara         IT   55000           4   55000         40
4  John      Sales   48000           1   48000         50
5  Neha         HR   52000           3   52000         60

In [ ]:
#drop multi cols
df.drop(["Name","Department"],axis=1,inplace = True)

In [45]:
df

   Salary  Experience  Amount  increment
0   50000           2   50000         10
1   45000           3   45000         20
2   60000           5   60000         30
3   55000           4   55000         40
4   48000           1   48000         50
5   52000           3   52000         60

In [46]:



import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [ ]:
#rows operation
df.loc[1,"Name"]

'Riya'

In [51]:
df.iloc[1,2]

'HR'

In [57]:
#get rows
df.loc[[0,2]]

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
2     103   Raj    Finance   60000           5

In [59]:
df.iloc[[1,2,3]]

   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4

In [60]:
# multi rows and cols
df.iloc[[0,1],[0,1]]

   Emp_ID  Name
0     101  Amit
1     102  Riya

In [61]:
df.iloc[0:2]

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3

In [62]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [66]:
#filter one greater
df[df['Emp_ID']>104]

   Emp_ID  Name Department  Salary  Experience
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [67]:
#30000 and 50000
df[(df['Salary']>30000) & (df['Salary']<50000)]

   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1

In [68]:
# # Sorting

# 1. df.sort_values("column_name") -> Sort by Single Column

# 2. df.sort_values("Age", ascending=True) -> Sort in Ascending Order

# 3. df.sort_values("Age", ascending=False) -> Sort in Descending Order

# 4. df.sort_values(["col1", "col2"]) -> Sort Multiple Columns

# 5. df.sort_values(["Age", "Salary"], ascending=[True, False]) -> Multiple Columns with Descending Order

In [69]:
import pandas as pd

data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}

df = pd.DataFrame(data)

print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3

In [ ]:
#sorting for ascending order
df.sort_values("Salary")

   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1
0     101  Amit         IT   50000           2
5     106  Neha         HR   52000           3
3     104  Sara         IT   55000           4
2     103   Raj    Finance   60000           5

In [71]:
#Two cols sort
df.sort_values(["Salary","Experience"])

   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1
0     101  Amit         IT   50000           2
5     106  Neha         HR   52000           3
3     104  Sara         IT   55000           4
2     103   Raj    Finance   60000           5

# Pandas Question

In [72]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     14 non-null     str
 1   gender   14 non-null     str
 2   physics  14 non-null     int64
 3   maths    14 non-null     int64
 4   english  14 non-null     int64
dtypes: int64(3), str(2)
memory usage: 692.0 bytes

In [74]:
df.head()

      name  gender  physics  maths  english
0     arun    Male       88     87       78
1   rajesh    Male       96    100       95
2  moorthy    Male       89     90       70
3     raja    Male       30     25       40
4     usha  Female       67     45       78

In [76]:
print(df.describe)

<bound method NDFrame.describe of        name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90>

In [78]:
df.isnull().sum()

name       0
gender     0
physics    0
maths      0
english    0
dtype: int64

In [80]:
df.rename(columns = {"name":"Name"})

       Name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [83]:
df.drop("name",axis =1)

    gender  physics  maths  english
0     Male       88     87       78
1     Male       96    100       95
2     Male       89     90       70
3     Male       30     25       40
4   Female       67     45       78
5   Female       56     46       78
6     Male       12     67       67
7   Female       78     71       67
8     Male       56     45       67
9   Female       71     90       23
10  Female      100    100      100
11    Male       78     55       47
12    Male       34     89       78
13  Female       67     88       90

In [84]:
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [87]:
df.iloc[1:4]

      name gender  physics  maths  english
1   rajesh   Male       96    100       95
2  moorthy   Male       89     90       70
3     raja   Male       30     25       40

In [88]:
df.loc[1,"name"]

'rajesh'

In [90]:
df["chemistry"] = df["physics"]
df

       name  gender  physics  maths  english  chemistry
0      arun    Male       88     87       78         88
1    rajesh    Male       96    100       95         96
2   moorthy    Male       89     90       70         89
3      raja    Male       30     25       40         30
4      usha  Female       67     45       78         67
5     priya  Female       56     46       78         56
6    Sundar    Male       12     67       67         12
7   Kavitha  Female       78     71       67         78
8    Dinesh    Male       56     45       67         56
9      Hema  Female       71     90       23         71
10    Gowri  Female      100    100      100        100
11      Ram    Male       78     55       47         78
12  Murugan    Male       34     89       78         34
13  Jenifer  Female       67     88       90         67

In [91]:
df[df['name'] == 'rajesh']

     name gender  physics  maths  english  chemistry
1  rajesh   Male       96    100       95         96

In [92]:
df[df['physics']>80]

       name  gender  physics  maths  english  chemistry
0      arun    Male       88     87       78         88
1    rajesh    Male       96    100       95         96
2   moorthy    Male       89     90       70         89
10    Gowri  Female      100    100      100        100

In [95]:
df[(df['physics']>50) & (df['maths'] < 90)]

       name  gender  physics  maths  english  chemistry
0      arun    Male       88     87       78         88
4      usha  Female       67     45       78         67
5     priya  Female       56     46       78         56
7   Kavitha  Female       78     71       67         78
8    Dinesh    Male       56     45       67         56
11      Ram    Male       78     55       47         78
13  Jenifer  Female       67     88       90         67

In [97]:
df.sort_values("physics")

       name  gender  physics  maths  english  chemistry
6    Sundar    Male       12     67       67         12
3      raja    Male       30     25       40         30
12  Murugan    Male       34     89       78         34
5     priya  Female       56     46       78         56
8    Dinesh    Male       56     45       67         56
13  Jenifer  Female       67     88       90         67
4      usha  Female       67     45       78         67
9      Hema  Female       71     90       23         71
11      Ram    Male       78     55       47         78
7   Kavitha  Female       78     71       67         78
0      arun    Male       88     87       78         88
2   moorthy    Male       89     90       70         89
1    rajesh    Male       96    100       95         96
10    Gowri  Female      100    100      100        100

In [98]:
df.sort_values("maths" ,ascending= False)

       name  gender  physics  maths  english  chemistry
1    rajesh    Male       96    100       95         96
10    Gowri  Female      100    100      100        100
9      Hema  Female       71     90       23         71
2   moorthy    Male       89     90       70         89
12  Murugan    Male       34     89       78         34
13  Jenifer  Female       67     88       90         67
0      arun    Male       88     87       78         88
7   Kavitha  Female       78     71       67         78
6    Sundar    Male       12     67       67         12
11      Ram    Male       78     55       47         78
5     priya  Female       56     46       78         56
4      usha  Female       67     45       78         67
8    Dinesh    Male       56     45       67         56
3      raja    Male       30     25       40         30

In [99]:
df.shape

(14, 6)

In [100]:
df[df['chemistry']>50]

       name  gender  physics  maths  english  chemistry
0      arun    Male       88     87       78         88
1    rajesh    Male       96    100       95         96
2   moorthy    Male       89     90       70         89
4      usha  Female       67     45       78         67
5     priya  Female       56     46       78         56
7   Kavitha  Female       78     71       67         78
8    Dinesh    Male       56     45       67         56
9      Hema  Female       71     90       23         71
10    Gowri  Female      100    100      100        100
11      Ram    Male       78     55       47         78
13  Jenifer  Female       67     88       90         67

In [103]:
df.iloc[1:2]

     name gender  physics  maths  english  chemistry
1  rajesh   Male       96    100       95         96